name: Deploy to Cloud Server

on:
  push:
    branches: [ "main" ]  # 仅在 main 分支推送时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # 配置到 GitHub Secrets
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@101.35.97.202 "
            cd /var/www/your-project &&
            git pull origin main &&
            pip install -r requirements.txt &&
            sudo systemctl restart your-service
          "
